// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9s0PfIPe4-lAMGAYg6Vzb-ILywZOPaJo',
    appId: '1:442094658019:web:58d223e5250095d1fd00d6',
    messagingSenderId: '442094658019',
    projectId: 'codeforany-80c1e',
    authDomain: 'codeforany-80c1e.firebaseapp.com',
    storageBucket: 'codeforany-80c1e.appspot.com',
    measurementId: 'G-8RE6VT39ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcYBkks0IHg0bZ3PxSWaydBdGJ7qZq_Q',
    appId: '1:442094658019:android:518a130eb1bba54efd00d6',
    messagingSenderId: '442094658019',
    projectId: 'codeforany-80c1e',
    storageBucket: 'codeforany-80c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkyw8Fto-HFwouIepDQu1fzSy-D3oNW7g',
    appId: '1:442094658019:ios:39f89ed7fdb23555fd00d6',
    messagingSenderId: '442094658019',
    projectId: 'codeforany-80c1e',
    storageBucket: 'codeforany-80c1e.appspot.com',
    iosClientId: '442094658019-uj07t3ini5onkkn7brir93vi8e0ek2mt.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.socketIoDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkyw8Fto-HFwouIepDQu1fzSy-D3oNW7g',
    appId: '1:442094658019:ios:0db74c72316c4c1dfd00d6',
    messagingSenderId: '442094658019',
    projectId: 'codeforany-80c1e',
    storageBucket: 'codeforany-80c1e.appspot.com',
    iosClientId: '442094658019-97rjl5gr3np6gf66m1kmnd6dc0689j1r.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.socketIoDemo.RunnerTests',
  );
}
